# ==========================================================
# Constants (screen size, gameplay, UI, themes)
# ==========================================================

# --------------------
# Window
# --------------------
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "PhaseDot"

# --------------------
# Gameplay
# --------------------
TARGET_FPS = 60
BASE_PLAYER_SPEED = 5
BASE_PLAYER_SIZE = 30
BASE_ENEMY_SPEED = 3
BASE_ENEMY_SIZE = 20
MIN_SPAWN_DISTANCE = 150

# --------------------
# Typography
# --------------------
TITLE_FONT_SIZE = 48
MENU_FONT_SIZE = 20
HUD_FONT_SIZE = 16

DEFAULT_FONT_NAME = "Kenney Future"
DEFAULT_FONT_PATH = ":resources:/fonts/ttf/Kenney/Kenney_Future.ttf"

# --------------------
# UI Layout
# --------------------
UI_PADDING = 12
UI_MARGIN = 8
UI_BORDER_RADIUS = 6
UI_BORDER_WIDTH = 2

# Animation / feel
UI_HOVER_SCALE = 1.05
UI_TRANSITION_SPEED = 0.15  # seconds

# --------------------
# Player Skins
# --------------------
PLAYER_SKINS = [
    {"color": (0, 229, 255), "size": BASE_PLAYER_SIZE, "speed": BASE_PLAYER_SPEED},
    {"color": (255, 100, 200), "size": BASE_PLAYER_SIZE - 5, "speed": BASE_PLAYER_SPEED + 1},  # unlockable
    {"color": (255, 255, 0), "size": BASE_PLAYER_SIZE - 10, "speed": BASE_PLAYER_SPEED + 2},  # unlockable
]

# --------------------
# Themes (colors generated by ChatGPT)
# --------------------
THEMES = {
    "NeonVoid": {
        # World
        "background": (11, 14, 20),
        "player": (0, 229, 255),
        "collectible": (0, 230, 118),

        # Enemy colors by difficulty
        "enemy_basic": (255, 100, 100),        # basic: soft red
        "enemy_intermediate": (255, 23, 68),   # intermediate: bright red
        "enemy_hard": (200, 0, 255),           # hard: purple

        # UI accents
        "accent": (255, 214, 0),

        # Text
        "text_primary": (235, 245, 255),
        "text_secondary": (160, 180, 200),

        # Buttons
        "button_base": (24, 28, 40),
        "button_hover": (45, 55, 80),
        "button_selected": (0, 229, 255),
        "button_disabled": (18, 20, 30),
        "button_border": (0, 229, 255),
        "button_border_selected": (0, 255, 255),

        # Panels
        "panel_background": (15, 18, 28)
    },

    "PhaseContrast": {
        # World
        "background": (13, 27, 42),
        "player": (241, 250, 238),
        "collectible": (168, 218, 220),

        # Enemy colors by difficulty
        "enemy_basic": (230, 100, 100),
        "enemy_intermediate": (230, 57, 70),
        "enemy_hard": (200, 0, 200),

        # UI accents
        "accent": (230, 57, 70),

        # Text
        "text_primary": (241, 250, 238),
        "text_secondary": (200, 220, 220),

        # Buttons
        "button_base": (30, 45, 65),
        "button_hover": (45, 70, 95),
        "button_selected": (230, 57, 70),
        "button_disabled": (25, 35, 50),
        "button_border": (230, 57, 70),

        # Panels
        "panel_background": (18, 32, 50)
    }
}
